### PR TITLE
fix(CSSCalc): Fix bug wherein spaces are omitted in calc() under certain circumstances and update various dependencies.

### PR DESCRIPTION
**Pull request by silbinarywolf**
- Update embedded CSSMin dependency (to handle URL rewriting)
- Add YUI Compressor port to composer.json (to fix calc() bug)
- Update JSMin dependency
- Remove unused/unneeded thirdparty php files

### CODE REVIEW

**Comment by SilbinaryWolf** [comment]
This might want/require a major version bump?

**Comment by SilbinaryWolf** [comment]
@nathancox Had a chance to look at this? The large amount of file changes is literally just removing unused thirdparty dependencies from your repo.

**Comment by nathancox** [comment]
Hi, sorry this took forever.  It kept falling through the cracks it seems.  Thanks for the updates!

**Comment by silbinarywolf** [comment]
No worries!

**Pull request merged**
